<template>
    <component :is="iconComponent" v-bind="$attrs" />
</template>

<script setup>
import { computed } from 'vue'
import {
    AdjustmentsHorizontalIcon,
    ArchiveBoxXMarkIcon,
    ArrowDownTrayIcon,
    ArrowLeftIcon,
    ArrowPathIcon,
    ArrowRightIcon,
    Bars3Icon,
    BellAlertIcon,
    BoltIcon,
    CalendarIcon,
    CalendarDaysIcon,
    ChatBubbleLeftEllipsisIcon,
    ExclamationTriangleIcon,
    RectangleGroupIcon,
    ChartBarIcon,
    CheckCircleIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpDownIcon,
    ChevronUpIcon,
    ClipboardDocumentListIcon,
    ClockIcon,
    Cog6ToothIcon,
    EllipsisVerticalIcon,
    EnvelopeIcon,
    EyeIcon,
    EyeSlashIcon,
    FunnelIcon,
    HomeIcon,
    LinkIcon,
    ArrowLeftStartOnRectangleIcon,
    MinusCircleIcon,
    NoSymbolIcon,
    PaperAirplaneIcon,
    PencilSquareIcon,
    PlusCircleIcon,
    QuestionMarkCircleIcon,
    ShieldCheckIcon,
    MagnifyingGlassIcon,
    Squares2X2Icon,
    SparklesIcon,
    SunIcon,
    SwatchIcon,
    TableCellsIcon,
    ArrowUpTrayIcon,
    UserIcon,
    UserPlusIcon,
    UsersIcon,
    TrophyIcon,
    WrenchIcon,
    XCircleIcon,
    XMarkIcon,
    SignalIcon,
    CircleStackIcon,
} from '@heroicons/vue/24/outline'
import { TrashIcon, CheckIcon, MoonIcon, StarIcon } from '@heroicons/vue/24/solid'

const props = defineProps({
    name: { type: String, required: true },
})

defineOptions({ inheritAttrs: false })

const iconMap = {
    'adjustments-horizontal': AdjustmentsHorizontalIcon,
    'archive-box-x-mark': ArchiveBoxXMarkIcon,
    download: ArrowDownTrayIcon,
    'arrow-left': ArrowLeftIcon,
    'arrow-path': ArrowPathIcon,
    'arrow-right': ArrowRightIcon,
    bars: Bars3Icon,
    'bell-alert': BellAlertIcon,
    bolt: BoltIcon,
    calendar: CalendarIcon,
    'calendar-days': CalendarDaysIcon,
    'chat-bubble-left-ellipsis': ChatBubbleLeftEllipsisIcon,
    'exclamation-triangle': ExclamationTriangleIcon,
    'rectangle-group': RectangleGroupIcon,
    'chart-bar': ChartBarIcon,
    'check-circle': CheckCircleIcon,
    'chevron-down': ChevronDownIcon,
    'chevron-left': ChevronLeftIcon,
    'chevron-right': ChevronRightIcon,
    'chevron-up': ChevronUpIcon,
    'chevron-up-down': ChevronUpDownIcon,
    'clipboard-list': ClipboardDocumentListIcon,
    clock: ClockIcon,
    cog: Cog6ToothIcon,
    'ellipsis-vertical': EllipsisVerticalIcon,
    envelope: EnvelopeIcon,
    eye: EyeIcon,
    'eye-slash': EyeSlashIcon,
    filter: FunnelIcon,
    home: HomeIcon,
    link: LinkIcon,
    logout: ArrowLeftStartOnRectangleIcon,
    'minus-circle': MinusCircleIcon,
    'no-symbol': NoSymbolIcon,
    'paper-airplane': PaperAirplaneIcon,
    'pencil-square': PencilSquareIcon,
    'plus-circle': PlusCircleIcon,
    'question-mark': QuestionMarkCircleIcon,
    'shield-check': ShieldCheckIcon,
    search: MagnifyingGlassIcon,
    squares: Squares2X2Icon,
    sparkles: SparklesIcon,
    sun: SunIcon,
    swatch: SwatchIcon,
    'table-cells': TableCellsIcon,
    upload: ArrowUpTrayIcon,
    user: UserIcon,
    'user-plus': UserPlusIcon,
    users: UsersIcon,
    signal: SignalIcon,
    'circle-stack': CircleStackIcon,
    trophy: TrophyIcon,
    wrench: WrenchIcon,
    'x-circle': XCircleIcon,
    'x-mark': XMarkIcon,
    bin: TrashIcon,
    check: CheckIcon,
    moon: MoonIcon,
    star: StarIcon,
}

const iconComponent = computed(() => iconMap[props.name])
</script>
