// Shared fixture for mounting ThemeBuilder.vue in unit tests.
// Mirrors ThemeTokens::colorDefaults() and ::colorCategories() — the shipped
// ShiftPlanner theme (sky brand ramp).
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

export const en = JSON.parse(
    readFileSync(resolve(process.cwd(), "resources/lang/en.json"), "utf8"),
);

const p = (light, dark) => ({ light, dark });

export const colors = {
    badge_custom_bg: p("indigo-100", "brand-900"),
    badge_custom_border: p("brand-200", "brand-800"),
    badge_custom_text: p("brand-700", "brand-300"),
    badge_error_bg: p("red-100", "red-900"),
    badge_error_border: p("red-200", "red-800"),
    badge_error_text: p("red-700", "red-300"),
    badge_muted_bg: p("zinc-100", "zinc-700"),
    badge_muted_border: p("zinc-200", "zinc-600"),
    badge_muted_text: p("zinc-400", "zinc-400"),
    badge_standard_bg: p("zinc-100", "zinc-800"),
    badge_standard_border: p("zinc-200", "zinc-700"),
    badge_standard_text: p("zinc-700", "zinc-300"),
    badge_success_bg: p("green-100", "green-900"),
    badge_success_border: p("green-200", "green-800"),
    badge_success_text: p("green-700", "green-300"),
    badge_warning_bg: p("yellow-100", "yellow-900"),
    badge_warning_border: p("yellow-200", "yellow-800"),
    badge_warning_text: p("yellow-700", "yellow-300"),
    brand_bg: p("indigo-600", "indigo-600"),
    brand_text: p("white", "white"),
    btn_primary_bg: p("brand-600", "brand-600"),
    btn_primary_text: p("white", "white"),
    btn_primary_border: p("transparent", "transparent"),
    btn_primary_hover_bg: p("brand-500", "brand-500"),
    btn_primary_hover_text: p("white", "white"),
    btn_primary_hover_border: p("transparent", "transparent"),
    btn_primary_disabled_bg: p("zinc-100", "zinc-800"),
    btn_primary_disabled_text: p("zinc-400", "zinc-600"),
    btn_primary_disabled_border: p("transparent", "transparent"),
    btn_secondary_bg: p("white", "zinc-800"),
    btn_secondary_text: p("zinc-950", "zinc-100"),
    btn_secondary_border: p("zinc-300", "zinc-600"),
    btn_secondary_hover_bg: p("zinc-50", "zinc-700"),
    btn_secondary_hover_text: p("zinc-950", "zinc-100"),
    btn_secondary_hover_border: p("zinc-300", "zinc-600"),
    btn_secondary_disabled_bg: p("zinc-100", "zinc-800"),
    btn_secondary_disabled_text: p("zinc-400", "zinc-600"),
    btn_secondary_disabled_border: p("transparent", "transparent"),
    btn_danger_bg: p("red-600", "red-600"),
    btn_danger_text: p("white", "white"),
    btn_danger_border: p("transparent", "transparent"),
    btn_danger_hover_bg: p("red-500", "red-500"),
    btn_danger_hover_text: p("white", "white"),
    btn_danger_hover_border: p("transparent", "transparent"),
    btn_danger_disabled_bg: p("zinc-100", "zinc-800"),
    btn_danger_disabled_text: p("zinc-400", "zinc-600"),
    btn_danger_disabled_border: p("transparent", "transparent"),
    separator_horizontal: { enabled: false, light: "zinc-200", dark: "zinc-700" },
    separator_vertical: { enabled: false, light: "zinc-200", dark: "zinc-700" },
    content_bg: p("white", "zinc-800"),
    content_text: p("zinc-700", "zinc-300"),
    dropdown_option_bg: p("white", "zinc-800"),
    dropdown_option_hover_bg: p("zinc-50", "zinc-700"),
    dropdown_option_hover_text: p("zinc-700", "zinc-300"),
    dropdown_option_selected_bg: p("indigo-50", "brand-900"),
    dropdown_option_selected_text: p("brand-700", "brand-300"),
    dropdown_option_text: p("zinc-700", "zinc-300"),
    dropdown_panel_bg: p("white", "zinc-800"),
    dropdown_panel_border: p("zinc-200", "zinc-700"),
    header_bg: p("brand-800", "brand-800"),
    header_text: p("brand-200", "indigo-200"),
    input_bg: p("white", "zinc-800"),
    input_border: p("zinc-300", "zinc-600"),
    input_disabled_bg: p("zinc-50", "zinc-900"),
    input_disabled_border: p("zinc-200", "zinc-700"),
    input_disabled_text: p("zinc-400", "zinc-600"),
    input_focus_border: p("brand-500", "brand-400"),
    input_focus_text: p("zinc-700", "zinc-300"),
    input_invalid_border: p("red-600", "red-600"),
    input_invalid_text: p("red-600", "red-600"),
    input_placeholder: p("zinc-400", "zinc-500"),
    input_text: p("zinc-700", "zinc-300"),
    menu_item_bg: p("transparent", "transparent"),
    menu_item_disabled_bg: p("transparent", "transparent"),
    menu_item_disabled_text: p("zinc-400", "zinc-600"),
    menu_item_hover_bg: p("zinc-100", "zinc-800"),
    menu_item_hover_text: p("brand-600", "brand-400"),
    menu_item_selected_bg: p("zinc-100", "zinc-800"),
    menu_item_selected_text: p("brand-600", "brand-400"),
    menu_item_text: p("zinc-700", "zinc-300"),
    overlay: p("black/40", "black/40"),
    pagination_active_bg: p("brand-600", "brand-600"),
    pagination_active_text: p("white", "white"),
    sidebar_bg: p("zinc-50", "zinc-900"),
    sidebar_text: p("zinc-400", "zinc-500"),
    surface_bg: p("white", "zinc-800"),
    surface_border: p("zinc-200", "zinc-700"),
    surface_secondary_bg: p("zinc-50", "zinc-900"),
    tab_active_bg: p("white", "zinc-800"),
    tab_active_border: p("brand-600", "brand-400"),
    tab_active_text: p("brand-600", "brand-400"),
    tab_bg: p("white", "zinc-800"),
    tab_hover_bg: p("zinc-50", "zinc-700"),
    tab_hover_border: p("zinc-200", "zinc-700"),
    tab_hover_text: p("zinc-700", "zinc-200"),
    tab_inactive_bg: p("white", "zinc-800"),
    tab_separator: p("zinc-200", "zinc-700"),
    tab_text: p("zinc-500", "zinc-400"),
    table_header_bg: p("zinc-50", "zinc-900"),
    table_header_separator: p("zinc-200", "zinc-700"),
    table_header_text: p("zinc-500", "zinc-400"),
    table_row_bg: p("white", "zinc-800"),
    table_row_hover_bg: p("zinc-50", "zinc-700"),
    table_row_hover_text: p("zinc-700", "zinc-300"),
    table_row_selected_bg: p("brand-50", "brand-900"),
    table_row_selected_text: p("brand-700", "indigo-300"),
    table_row_separator: p("zinc-200", "zinc-700"),
    table_row_text: p("zinc-700", "zinc-300"),
    text_heading: p("zinc-700", "zinc-200"),
    text_link: p("brand-600", "brand-500"),
    text_link_hover: p("brand-500", "brand-400"),
    text_muted: p("zinc-400", "zinc-500"),
    text_primary: p("zinc-700", "zinc-300"),
};

const humanize = (k) => k.charAt(0).toUpperCase() + k.slice(1).replaceAll("_", " ");
const items = (keys) => keys.map((key) => ({ key, label: humanize(key) }));

// Mirrors ThemeTokens::colorCategories().
export const categories = [
    { key: "chrome", label: "Chrome", colors: items([
        "header_bg", "header_text", "sidebar_bg", "sidebar_text",
        "content_bg", "content_text",
        "separator_horizontal", "separator_vertical",
    ]) },
    { key: "menu", label: "Menu", colors: items([
        "menu_item_bg", "menu_item_text",
        "menu_item_hover_bg", "menu_item_hover_text",
        "menu_item_selected_bg", "menu_item_selected_text",
        "menu_item_disabled_bg", "menu_item_disabled_text",
    ]) },
    { key: "text", label: "Text", colors: items([
        "text_heading", "text_primary", "text_muted",
        "text_link", "text_link_hover",
    ]) },
    { key: "buttons", label: "Buttons", colors: items([
        "btn_primary_bg", "btn_primary_text", "btn_primary_border",
        "btn_primary_hover_bg", "btn_primary_hover_text", "btn_primary_hover_border",
        "btn_primary_disabled_bg", "btn_primary_disabled_text", "btn_primary_disabled_border",
        "btn_secondary_bg", "btn_secondary_text", "btn_secondary_border",
        "btn_secondary_hover_bg", "btn_secondary_hover_text", "btn_secondary_hover_border",
        "btn_secondary_disabled_bg", "btn_secondary_disabled_text", "btn_secondary_disabled_border",
        "btn_danger_bg", "btn_danger_text", "btn_danger_border",
        "btn_danger_hover_bg", "btn_danger_hover_text", "btn_danger_hover_border",
        "btn_danger_disabled_bg", "btn_danger_disabled_text", "btn_danger_disabled_border",
    ]) },
    { key: "tabs", label: "Tabs", colors: items([
        "tab_bg", "tab_text", "tab_separator", "tab_inactive_bg",
        "tab_active_bg", "tab_active_text", "tab_active_border",
        "tab_hover_bg", "tab_hover_text", "tab_hover_border",
    ]) },
    { key: "table", label: "Table", colors: items([
        "table_header_bg", "table_header_text", "table_header_separator",
        "table_row_bg", "table_row_text", "table_row_separator",
        "table_row_hover_bg", "table_row_hover_text",
        "table_row_selected_bg", "table_row_selected_text",
        "pagination_active_bg", "pagination_active_text",
    ]) },
    { key: "forms", label: "Forms", colors: items([
        "input_bg", "input_text", "input_border", "input_placeholder",
        "input_focus_border", "input_focus_text",
        "input_disabled_bg", "input_disabled_text", "input_disabled_border",
        "input_invalid_border", "input_invalid_text",
        "dropdown_panel_bg", "dropdown_panel_border",
        "dropdown_option_bg", "dropdown_option_text",
        "dropdown_option_hover_bg", "dropdown_option_hover_text",
        "dropdown_option_selected_bg", "dropdown_option_selected_text",
    ]) },
    { key: "status", label: "Status & feedback", colors: items([
        "badge_success_bg", "badge_success_text", "badge_success_border",
        "badge_warning_bg", "badge_warning_text", "badge_warning_border",
        "badge_error_bg", "badge_error_text", "badge_error_border",
        "badge_custom_bg", "badge_custom_text", "badge_custom_border",
        "badge_standard_bg", "badge_standard_text", "badge_standard_border",
        "badge_muted_bg", "badge_muted_text", "badge_muted_border",
    ]) },
    { key: "surface", label: "Surface", colors: items([
        "surface_bg", "surface_secondary_bg", "surface_border", "overlay",
    ]) },
];

export const themeBuilderProps = {
    categories,
    colors,
    defaultColors: colors,
    brandFamily: "sky",
    defaultBrandFamily: "sky",
};
